config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  get 'search', to: 'questions#search'
  patch 'bestanswer', to: 'questions#bestanswer'
  resources :questions do
    resources :answers, only: [:create, :destroy]
  end
  resources :bookmarks, only: [:create, :destroy]
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update]
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_users, through: :bookmarks, source: :user
  belongs_to :user
  validates :title, presence: true, length: { in: 1..126 }
  validates :content, presence: true, length: { in: 1..3000 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :bestanswer]

  def search
    params[:q]['title_or_content_cont_all'] = params[:q]['title_or_content_cont_all'].split(/[\p{blank}\s]+/)
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true).order(id: "DESC") #.page(params[:page]).per(10)
    @questions_open = @questions.where(best_answer_id:nil).order(id: "DESC") #.page(params[:page]).per(10)
    @questions_close = @questions.where.not(best_answer_id:nil).order(id: "DESC") #.page(params[:page]).per(10)
    render :index
  end

  def index

    @questions = Question.all.order(id: "DESC") #.page(params[:page]).per(10)
    @questions_open = @questions.where(best_answer_id:nil).order(id: "DESC") #.page(params[:page]).per(10)
    @questions_close = @questions.where.not(best_answer_id:nil).order(id: "DESC") #.page(params[:page]).per(10)
  end

  def show
    if user_signed_in?
      @bookmark = current_user.bookmarks.find_by(question_id: @question.id)
      @comment = Comment.new
    end
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to @question, notice: '質問を登録しました'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: '質問を編集しました。'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice:"質問を削除しました！"
  end

  def bestanswer
    @question = Question.find(question_params[:id])
    @question.update(question_params)
    redirect_to @question, notice: 'ベストアンサーが選べられました'
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :content, :user_id, :best_answer_id, :id)
  end


end

app/views/questions/_form.html.erb
<br><br>

<%= form_with(model: @question, local: true) do |form| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> バリデーションエラーが発生しています</h2>
      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title , placeholder: "質問のタイトルを記入..." ,class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.text_area :content,:size => "50x20", placeholder: "質問内容を記入（マークダウン記法が使えます）...", class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "決定",class:"btn btn-success"%>
  </div>
<% end %>

app/views/questions/_search_form.html.erb
<%= search_form_for(@q,url:search_path , class:"form-inline")do |f| %>
    <%= f.search_field :title_or_content_cont_all, placeholder: "質問を検索...", class: "form-control" %>
    <%= f.submit "検索", class: "btn btn-secondary" %>
<% end %>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item"><a href="#tab1" class="nav-link active" data-toggle="tab">新着</a></li>
  <li class="nav-item"><a href="#tab2" class="nav-link" data-toggle="tab">回答受付中</a></li>
  <li class="nav-item"><a href="#tab3" class="nav-link" data-toggle="tab">質問解決済</a></li>
</ul>

<div class="tab-content">
  <div id="tab1" class="tab-pane active">
    <table class="table table-hover">
      <% @questions.each do |question| %>
      <tbody>
        <tr>
          <% if question.best_answer_id.present? %>
            <td  class="td-category"><div class="btn btn-info">質問<br>解決済<div></td>
          <% else %>
            <td  class="td-category"><div class="btn btn-danger">回答<br>受付中<div></td>
          <% end %>

          <td   class="td-title"><%= link_to question.title ,question_path(question) ,class:"article-title"%><br><br>
            <%= link_to question.user.name ,user_path(question.user_id) %>　が<%= question.created_at.strftime("%Y/%m/%d")  %>に投稿<br>
            回答：<%= question.answers.count %> 件・ブックマーク：<%= question.bookmarks.count %> 件
          </td>

        </tr>
      </tbody>
    <% end %>
    </table>
  </div>

  <div id="tab2" class="tab-pane">
    <table class="table table-hover">
      <% @questions_open.each do |question| %>
      <tbody>
        <tr>
          <% if question.best_answer_id.present? %>
            <td  class="td-category"><div class="btn btn-info">質問<br>解決済<div></td>
          <% else %>
            <td  class="td-category"><div class="btn btn-danger">回答<br>受付中<div></td>
          <% end %>
          <td class="td-title"><%= link_to question.title ,question_path(question) ,class:"article-title"%><br><br>
            <%= link_to question.user.name ,user_path(question.user_id) %>　が<%= question.created_at.strftime("%Y/%m/%d")  %>に投稿<br>
            回答：<%= question.answers.count %> 件・ブックマーク：<%= question.bookmarks.count %> 件
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>

  <div id="tab3" class="tab-pane">
    <div id="tab2" class="tab-pane">
      <table class="table table-hover">
        <% @questions_close.each do |question| %>
        <tbody>
          <tr>
            <% if question.best_answer_id.present? %>
              <td  class="td-category"><div class="btn btn-info">質問<br>解決済<div></td>
            <% else %>
              <td  class="td-category"><div class="btn btn-danger">回答<br>受付中<div></td>
            <% end %>
            <td class="td-title"><%= link_to question.title ,question_path(question) ,class:"article-title"%><br><br>
              <%= link_to question.user.name ,user_path(question.user_id) %>　が<%= question.created_at.strftime("%Y/%m/%d")  %>に投稿<br>
              回答：<%= question.answers.count %> 件・ブックマーク：<%= question.bookmarks.count %> 件
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<%= link_to '戻る', questions_path ,class:"btn btn-info" %>
<% if user_signed_in? %>
  <% if current_user.id == @question.user_id %>
    <%= link_to '編集', edit_question_path(@question) ,class:"btn btn-success" %>
    <%= link_to '削除', @question, method: :delete, data: { confirm: '本当に削除しますか？' } ,class:"btn btn-danger"%>
  <% end %>

  <% unless @question.user_id == current_user.id %>
    <% if @bookmark.present? %>
      <%= link_to 'お気に入り解除する', bookmark_path(id: @bookmark.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', bookmarks_path(question_id: @question.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<% end %>

<br><br>

<div class="card">
  <h3 class="card-header question-title"><%= @question.title %></h3>
  <div class="card-body">
    <p class="card-text"><%= markdown(@question.content).html_safe %></p>
  </div>
</div>

<br><br>

<% unless @question.answers.count.zero? %>
  <h1 class="question-answer">■回答一覧（回答：<%= @question.answers.count.to_s + "件" %>）</h1>
  <%= render @question.answers %>
<% else %>
  <h1 class="question-answer">■回答一覧（回答：<%= @question.answers.count.to_s + "件" %>）</h1>
  <div>回答はありません</div>
<% end %>

<br><br>

<h1 class="question-answer">■回答を投稿</h1>
<% if user_signed_in? %>
  <p><%= render 'answers/form', question: @question %></p>
<% else %>
  <div>回答するにはログインが必要です。</div>
<% end %>