config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  get 'search', to: 'questions#search'
  patch 'bestanswer', to: 'questions#bestanswer'
  resources :questions do
    resources :answers, only: [:create, :destroy]
  end
  resources :bookmarks, only: [:create, :destroy]
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :answer
  belongs_to :user

  validates :content, presence: true, length: { in: 1..1048 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(comment_params)
    @answer = Answer.find(@comment.answer_id)
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to question_path(@answer.question_id), notice: '投稿できませんでした...' }
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @answer = Answer.find(@comment.answer_id)
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @answer = Answer.find(@comment.answer_id)
    @comment.destroy
    redirect_to question_path(@answer.question_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :answer_id, :user_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<% if user_signed_in? %>
  <%= form_with(model:[comment]) do |f| %>
  <% if comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
    <ul>
    <% comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
    <%= f.text_field :content , id: "comment_content_#{comment.id}" , class: "form-control"%>

  </div>
    <%= f.submit 'コメントする' %>
    <% end %>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
  <%= form_with(model:[comment]) do |f| %>

  <div class="field">
    <%= f.text_field :content , placeholder: "コメントを投稿しよう...", class: "form-control"%>
    <%= f.hidden_field :user_id, :value => current_user.id  %>
    <%= f.hidden_field :answer_id, :value => answer.id  %>
  </div>
    <%= f.submit 'コメントする' %>
  <% end %>
<% end %>

app/views/comments/_index.html.erb
<% answer.comments.each do |comment| %>
<table class="table table-hover">
  <tbody>
    <tr>
      <td><%= comment.user.name %></td>
      <td><%= comment.content %></td>
      <td>
        <% if user_signed_in? %>
          <% if current_user.id == comment.user_id %>
            <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
            <%= link_to "コメント編集", edit_comment_path(comment), remote: true %>
            <%= link_to 'コメント削除', comment, method: :delete, data: { confirm: '本当に削除しますか'  } %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>
<% end %>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', comment: @comment %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { answer: @answer }) %>")
$("textarea").val('')