config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  get 'search', to: 'questions#search'
  patch 'bestanswer', to: 'questions#bestanswer'
  resources :questions do
    resources :answers, only: [:create, :destroy]
  end
  resources :bookmarks, only: [:create, :destroy]
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  mount_uploader :icon, ImageUploader
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :answer_questions, through: :answers, source: :question
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_questions, through: :bookmarks, source: :question
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :search_default
  before_action :set_user
  before_action :authenticate_user!, only: [:show, :edit, :update]

  def show
    @questions = @user.questions
    @answers = @user.answer_questions
    @bookmarks = @user.bookmark_questions
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました！"
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation, :icon, :icon_cache, :profile)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<br>
<div class="card mx-autor">
  <h2 class="card-header">プロフィール編集</h2>
  <div class="card-body">

    <%= form_with(model: @user, local: true) do |f| %>
    <div class="form-group">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name ,class:"form-control"%>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email ,class:"form-control"%>
      </div>

      <div class="form-group">
        <%= f.file_field :icon %>
        <%= f.hidden_field :icon_cache %>
        <br>
        <%= image_tag(@user.icon.url,:size => "300x300") if @user.icon && @user.icon.url %>

      </div>

      <div class="form-group">
        <%= f.label :profile %>
        <%= f.text_area :profile ,class:"form-control" %>
      </div>

      <div class="actions">
        <%= f.submit '完了',class:"btn btn-primary btn-block" %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<br>
<div class="card  mx-auto">
  <div class="card-header ">
    <%= @user.name %>のプロフィール
  </div>

  <div class="card-body">
    <% if @user.icon.file.present? %>
    <%= image_tag @user.icon.url,:size => "300x300" %>
    <% else %>
    <%= image_tag("default.png", :size => "300x300") %>
    <% end %>

    <% if current_user.id == @user.id %>
    <p><br>
      <%= link_to 'プロフィール編集', edit_user_path(@user.id) , class: 'btn btn-primary'%>
      <% end %>
    </p>

    <table class="table table-bordered">
      <tbody>
        <tr>
          <td class="td-profile">メールアドレス</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td class="td-profile">自己紹介</td>
          <td><%= @user.profile %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<br>

<ul class="nav nav-tabs">
  <li class="nav-item"><a href="#tab1" class="nav-link active" data-toggle="tab">質問投稿</a></li>
  <li class="nav-item"><a href="#tab2" class="nav-link" data-toggle="tab">回答投稿</a></li>
  <li class="nav-item"><a href="#tab3" class="nav-link" data-toggle="tab">ブックマーク</a></li>
</ul>

<div class="tab-content">
  <div id="tab1" class="tab-pane active">
    <table class="table table-hover">
      <% @questions.each do |question| %>
      <tbody>
        <tr>
          <% if question.best_answer_id.present? %>
            <td  class="td-category"><div class="btn btn-info">質問<br>解決済<div></td>
          <% else %>
            <td  class="td-category"><div class="btn btn-danger">回答<br>受付中<div></td>
          <% end %>

          <td class="td-title"><%= link_to question.title ,question_path(question) ,class:"article-title"%><br><br>
            <%= link_to question.user.name ,user_path(question.user_id) %>　が<%= question.created_at.strftime("%Y/%m/%d")  %>に投稿<br>
            回答：<%= question.answers.count %> 件・ブックマーク：<%= question.bookmarks.count %> 件
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>

  <div id="tab2" class="tab-pane">
    <table class="table table-hover">
      <% @answers.each do |question| %>
      <tbody>
        <tr>
          <% if question.best_answer_id.present? %>
            <td class="td-category"><div class="btn btn-info">質問<br>解決済<div></td>
          <% else %>
            <td  class="td-category"><div class="btn btn-danger">回答<br>受付中<div></td>
          <% end %>

          <td class="td-title"><%= link_to question.title ,question_path(question) ,class:"article-title"%><br><br>
            <%= link_to question.user.name ,user_path(question.user_id) %>　が<%= question.created_at.strftime("%Y/%m/%d")  %>に投稿<br>
            回答：<%= question.answers.count %> 件・ブックマーク：<%= question.bookmarks.count %> 件
          </td>

        </tr>
      </tbody>
      <% end %>
    </table>
  </div>

  <div id="tab3" class="tab-pane">
    <div id="tab2" class="tab-pane">
      <table class="table table-hover">
        <% @bookmarks.each do |question| %>
        <tbody>
          <tr>
            <% if question.best_answer_id.present? %>
              <td  class="td-category"><div class="btn btn-info">質問<br>解決済<div></td>
            <% else %>
              <td  class="td-category"><div class="btn btn-danger">回答<br>受付中<div></td>
            <% end %>

            <td class="td-title"><%= link_to question.title ,question_path(question) ,class:"article-title"%><br><br>
              <%= link_to question.user.name ,user_path(question.user_id) %>　が<%= question.created_at.strftime("%Y/%m/%d")  %>に投稿<br>
              回答：<%= question.answers.count %> 件・ブックマーク：<%= question.bookmarks.count %> 件
            </td>

          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>