config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  get 'search', to: 'questions#search'
  patch 'bestanswer', to: 'questions#bestanswer'
  resources :questions do
    resources :answers, only: [:create, :destroy]
  end
  resources :bookmarks, only: [:create, :destroy]
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solque</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark"  style="background-color:#008080;" >
      <div class="container">
        <%= link_to 'SolQue', root_path, class:"navbar-brand" %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-sample">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar-sample">



          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <% if controller.controller_name == "questions" %>

              <%= render 'search_form' %>
              <% end %>

            </li>
          </ul>

           <ul class="navbar-nav">
            <li class="nav-item">
            <% if user_signed_in? %>
              <%= link_to '質問' ,new_question_path, class:"navbar-brand" %>
              <%= link_to 'マイページ' ,user_path(current_user.id), class:"navbar-brand" %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete , class:"navbar-brand"%>
            <% else %>
              <%= link_to 'ログイン', new_user_session_path , class:"navbar-brand"%>
              <%= link_to 'サインアップ', new_user_registration_path , class:"navbar-brand"%>
            <% end %>

            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <br>
    <%= yield %>
        </div>
  </body>
</html>